# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-03-12 06:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsGPS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atitle', models.CharField(max_length=24, verbose_name='地区')),
                ('gps', models.IntegerField(max_length=8, verbose_name='地理位置')),
                ('aparent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsGPS')),
            ],
            options={
                'verbose_name': '位置定位',
                'verbose_name_plural': '位置定位',
                'db_table': 'goods_gps',
            },
        ),
    ]
