# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-03-16 10:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_auto_20190312_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atitle', models.CharField(max_length=24, verbose_name='地区')),
                ('aparent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.Area')),
            ],
            options={
                'verbose_name': '地区',
                'verbose_name_plural': '地区',
                'db_table': 'area',
            },
        ),
        migrations.CreateModel(
            name='AreaGps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gps', models.IntegerField(null=True, verbose_name='地理位置')),
                ('area', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='goods.Area')),
            ],
            options={
                'verbose_name': '地区坐标',
                'verbose_name_plural': '地区坐标',
                'db_table': 'area_gps',
            },
        ),
        migrations.RemoveField(
            model_name='goodsgps',
            name='aparent',
        ),
        migrations.DeleteModel(
            name='GoodsGPS',
        ),
    ]
