# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-03-19 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_auto_20190316_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areagps',
            name='gps',
        ),
        migrations.AddField(
            model_name='areagps',
            name='gps_x',
            field=models.IntegerField(null=True, verbose_name='地理位置X轴'),
        ),
        migrations.AddField(
            model_name='areagps',
            name='gps_y',
            field=models.IntegerField(null=True, verbose_name='地理位置Y轴'),
        ),
    ]
